app = 'novaproof-api'
primary_region = 'ewr'

[build]
  no-cache = true

[env]
  PORT = "3100"
  NODE_ENV = "production"
  CONTRACT_ADDRESS = "0xA88CBE718eAF91EDe4304a595f88069fA214fce6"
  BASE_RPC_URL = "https://base-mainnet.g.alchemy.com/v2/sHcreRgIM4yb_QuIEr335"
  CHAIN_ID = "8453"

[http_service]
  internal_port = 3100
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
